spring:
  application:
    name: API-GATEWAY

server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
#    account-service:
#      path: /ticket/**
#      serviceId: TICKET-SERVICE
    customer-service:
      path: /product/**
      serviceId: PRODUCT-SERVICE
    config-server:
      path: /configserver/**
      serviceId: CONFIG-SERVER
    host:
      socket-timeout-millis: 30000